//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.17 at 12:55:15 PM IST 
//


package com.cci.payment.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AccountInfoResponseRecordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountInfoResponseRecordType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TrackingID" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="BAN"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="30"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FirstName" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="28"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LastName" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="56"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AccountName"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="50"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="BillCity"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="35"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="BillState"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="28"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="BillCountry"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="15"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CreditClass"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="5"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CpniPin"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9][0-9][0-9][0-9]"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AccountCategory"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="15"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AccountStatus"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="NEW"/&gt;
 *               &lt;enumeration value="CURRENT"/&gt;
 *               &lt;enumeration value="DISC_REQ"/&gt;
 *               &lt;enumeration value="DISC_DONE"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="VIPCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="InCollections" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="IsSuspended" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="HasKansysContract" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="EarliestAllowableDueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="LatestAllowableDueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="ExtensionMaxBalance" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="LastBillDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="LastBillAmount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="CurrentDueBalance" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="PastDueBalance" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="PaymentDueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="MaxOverpaymentAmount" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="LastPaymentAmount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="LastPaymentDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="CashOnly" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ExtendedDueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountInfoResponseRecordType", propOrder = {
    "trackingID",
    "ban",
    "firstName",
    "lastName",
    "accountName",
    "billCity",
    "billState",
    "billCountry",
    "creditClass",
    "cpniPin",
    "accountCategory",
    "accountStatus",
    "vipCode",
    "inCollections",
    "isSuspended",
    "hasKansysContract",
    "earliestAllowableDueDate",
    "latestAllowableDueDate",
    "extensionMaxBalance",
    "lastBillDate",
    "lastBillAmount",
    "currentDueBalance",
    "pastDueBalance",
    "paymentDueDate",
    "maxOverpaymentAmount",
    "lastPaymentAmount",
    "lastPaymentDate",
    "cashOnly",
    "extendedDueDate"
})
public class AccountInfoResponseRecordType {

    @XmlElement(name = "TrackingID")
    protected long trackingID;
    @XmlElement(name = "BAN", required = true)
    protected String ban;
    @XmlElement(name = "FirstName")
    protected String firstName;
    @XmlElement(name = "LastName")
    protected String lastName;
    @XmlElement(name = "AccountName", required = true)
    protected String accountName;
    @XmlElement(name = "BillCity", required = true)
    protected String billCity;
    @XmlElement(name = "BillState", required = true)
    protected String billState;
    @XmlElement(name = "BillCountry", required = true)
    protected String billCountry;
    @XmlElement(name = "CreditClass", required = true)
    protected String creditClass;
    @XmlElement(name = "CpniPin", required = true)
    protected String cpniPin;
    @XmlElement(name = "AccountCategory", required = true)
    protected String accountCategory;
    @XmlElement(name = "AccountStatus", required = true)
    protected String accountStatus;
    @XmlElement(name = "VIPCode", required = true)
    protected String vipCode;
    @XmlElement(name = "InCollections")
    protected boolean inCollections;
    @XmlElement(name = "IsSuspended")
    protected boolean isSuspended;
    @XmlElement(name = "HasKansysContract")
    protected boolean hasKansysContract;
    @XmlElement(name = "EarliestAllowableDueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar earliestAllowableDueDate;
    @XmlElement(name = "LatestAllowableDueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar latestAllowableDueDate;
    @XmlElement(name = "ExtensionMaxBalance")
    protected long extensionMaxBalance;
    @XmlElement(name = "LastBillDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastBillDate;
    @XmlElement(name = "LastBillAmount")
    protected Long lastBillAmount;
    @XmlElement(name = "CurrentDueBalance")
    protected long currentDueBalance;
    @XmlElement(name = "PastDueBalance")
    protected long pastDueBalance;
    @XmlElement(name = "PaymentDueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar paymentDueDate;
    @XmlElement(name = "MaxOverpaymentAmount")
    protected long maxOverpaymentAmount;
    @XmlElement(name = "LastPaymentAmount")
    protected Long lastPaymentAmount;
    @XmlElement(name = "LastPaymentDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastPaymentDate;
    @XmlElement(name = "CashOnly")
    protected boolean cashOnly;
    @XmlElement(name = "ExtendedDueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar extendedDueDate;

    /**
     * Gets the value of the trackingID property.
     * 
     */
    public long getTrackingID() {
        return trackingID;
    }

    /**
     * Sets the value of the trackingID property.
     * 
     */
    public void setTrackingID(long value) {
        this.trackingID = value;
    }

    /**
     * Gets the value of the ban property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBAN() {
        return ban;
    }

    /**
     * Sets the value of the ban property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBAN(String value) {
        this.ban = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the accountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * Sets the value of the accountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountName(String value) {
        this.accountName = value;
    }

    /**
     * Gets the value of the billCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillCity() {
        return billCity;
    }

    /**
     * Sets the value of the billCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillCity(String value) {
        this.billCity = value;
    }

    /**
     * Gets the value of the billState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillState() {
        return billState;
    }

    /**
     * Sets the value of the billState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillState(String value) {
        this.billState = value;
    }

    /**
     * Gets the value of the billCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillCountry() {
        return billCountry;
    }

    /**
     * Sets the value of the billCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillCountry(String value) {
        this.billCountry = value;
    }

    /**
     * Gets the value of the creditClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditClass() {
        return creditClass;
    }

    /**
     * Sets the value of the creditClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditClass(String value) {
        this.creditClass = value;
    }

    /**
     * Gets the value of the cpniPin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpniPin() {
        return cpniPin;
    }

    /**
     * Sets the value of the cpniPin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpniPin(String value) {
        this.cpniPin = value;
    }

    /**
     * Gets the value of the accountCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountCategory() {
        return accountCategory;
    }

    /**
     * Sets the value of the accountCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountCategory(String value) {
        this.accountCategory = value;
    }

    /**
     * Gets the value of the accountStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountStatus() {
        return accountStatus;
    }

    /**
     * Sets the value of the accountStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountStatus(String value) {
        this.accountStatus = value;
    }

    /**
     * Gets the value of the vipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVIPCode() {
        return vipCode;
    }

    /**
     * Sets the value of the vipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVIPCode(String value) {
        this.vipCode = value;
    }

    /**
     * Gets the value of the inCollections property.
     * 
     */
    public boolean isInCollections() {
        return inCollections;
    }

    /**
     * Sets the value of the inCollections property.
     * 
     */
    public void setInCollections(boolean value) {
        this.inCollections = value;
    }

    /**
     * Gets the value of the isSuspended property.
     * 
     */
    public boolean isIsSuspended() {
        return isSuspended;
    }

    /**
     * Sets the value of the isSuspended property.
     * 
     */
    public void setIsSuspended(boolean value) {
        this.isSuspended = value;
    }

    /**
     * Gets the value of the hasKansysContract property.
     * 
     */
    public boolean isHasKansysContract() {
        return hasKansysContract;
    }

    /**
     * Sets the value of the hasKansysContract property.
     * 
     */
    public void setHasKansysContract(boolean value) {
        this.hasKansysContract = value;
    }

    /**
     * Gets the value of the earliestAllowableDueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEarliestAllowableDueDate() {
        return earliestAllowableDueDate;
    }

    /**
     * Sets the value of the earliestAllowableDueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEarliestAllowableDueDate(XMLGregorianCalendar value) {
        this.earliestAllowableDueDate = value;
    }

    /**
     * Gets the value of the latestAllowableDueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLatestAllowableDueDate() {
        return latestAllowableDueDate;
    }

    /**
     * Sets the value of the latestAllowableDueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLatestAllowableDueDate(XMLGregorianCalendar value) {
        this.latestAllowableDueDate = value;
    }

    /**
     * Gets the value of the extensionMaxBalance property.
     * 
     */
    public long getExtensionMaxBalance() {
        return extensionMaxBalance;
    }

    /**
     * Sets the value of the extensionMaxBalance property.
     * 
     */
    public void setExtensionMaxBalance(long value) {
        this.extensionMaxBalance = value;
    }

    /**
     * Gets the value of the lastBillDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastBillDate() {
        return lastBillDate;
    }

    /**
     * Sets the value of the lastBillDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastBillDate(XMLGregorianCalendar value) {
        this.lastBillDate = value;
    }

    /**
     * Gets the value of the lastBillAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLastBillAmount() {
        return lastBillAmount;
    }

    /**
     * Sets the value of the lastBillAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLastBillAmount(Long value) {
        this.lastBillAmount = value;
    }

    /**
     * Gets the value of the currentDueBalance property.
     * 
     */
    public long getCurrentDueBalance() {
        return currentDueBalance;
    }

    /**
     * Sets the value of the currentDueBalance property.
     * 
     */
    public void setCurrentDueBalance(long value) {
        this.currentDueBalance = value;
    }

    /**
     * Gets the value of the pastDueBalance property.
     * 
     */
    public long getPastDueBalance() {
        return pastDueBalance;
    }

    /**
     * Sets the value of the pastDueBalance property.
     * 
     */
    public void setPastDueBalance(long value) {
        this.pastDueBalance = value;
    }

    /**
     * Gets the value of the paymentDueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaymentDueDate() {
        return paymentDueDate;
    }

    /**
     * Sets the value of the paymentDueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPaymentDueDate(XMLGregorianCalendar value) {
        this.paymentDueDate = value;
    }

    /**
     * Gets the value of the maxOverpaymentAmount property.
     * 
     */
    public long getMaxOverpaymentAmount() {
        return maxOverpaymentAmount;
    }

    /**
     * Sets the value of the maxOverpaymentAmount property.
     * 
     */
    public void setMaxOverpaymentAmount(long value) {
        this.maxOverpaymentAmount = value;
    }

    /**
     * Gets the value of the lastPaymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLastPaymentAmount() {
        return lastPaymentAmount;
    }

    /**
     * Sets the value of the lastPaymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLastPaymentAmount(Long value) {
        this.lastPaymentAmount = value;
    }

    /**
     * Gets the value of the lastPaymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastPaymentDate() {
        return lastPaymentDate;
    }

    /**
     * Sets the value of the lastPaymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastPaymentDate(XMLGregorianCalendar value) {
        this.lastPaymentDate = value;
    }

    /**
     * Gets the value of the cashOnly property.
     * 
     */
    public boolean isCashOnly() {
        return cashOnly;
    }

    /**
     * Sets the value of the cashOnly property.
     * 
     */
    public void setCashOnly(boolean value) {
        this.cashOnly = value;
    }

    /**
     * Gets the value of the extendedDueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExtendedDueDate() {
        return extendedDueDate;
    }

    /**
     * Sets the value of the extendedDueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExtendedDueDate(XMLGregorianCalendar value) {
        this.extendedDueDate = value;
    }

}
