//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.17 at 12:55:15 PM IST 
//


package com.cci.payment.stub;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cci.payment.stub package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PayAndRestoreRequestRecordTypeFeeAmount_QNAME = new QName("http://www.consolidated.com/cpi", "FeeAmount");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cci.payment.stub
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccountInfo }
     * 
     */
    public AccountInfo createAccountInfo() {
        return new AccountInfo();
    }

    /**
     * Create an instance of {@link AccountInfoRequestType }
     * 
     */
    public AccountInfoRequestType createAccountInfoRequestType() {
        return new AccountInfoRequestType();
    }

    /**
     * Create an instance of {@link AccountInfoResponse }
     * 
     */
    public AccountInfoResponse createAccountInfoResponse() {
        return new AccountInfoResponse();
    }

    /**
     * Create an instance of {@link AccountInfoOutputType }
     * 
     */
    public AccountInfoOutputType createAccountInfoOutputType() {
        return new AccountInfoOutputType();
    }

    /**
     * Create an instance of {@link PayAndRestore }
     * 
     */
    public PayAndRestore createPayAndRestore() {
        return new PayAndRestore();
    }

    /**
     * Create an instance of {@link PayAndRestoreRequestType }
     * 
     */
    public PayAndRestoreRequestType createPayAndRestoreRequestType() {
        return new PayAndRestoreRequestType();
    }

    /**
     * Create an instance of {@link PayAndRestoreResponse }
     * 
     */
    public PayAndRestoreResponse createPayAndRestoreResponse() {
        return new PayAndRestoreResponse();
    }

    /**
     * Create an instance of {@link PayAndRestoreOutputType }
     * 
     */
    public PayAndRestoreOutputType createPayAndRestoreOutputType() {
        return new PayAndRestoreOutputType();
    }

    /**
     * Create an instance of {@link Deposit }
     * 
     */
    public Deposit createDeposit() {
        return new Deposit();
    }

    /**
     * Create an instance of {@link DepositRequestType }
     * 
     */
    public DepositRequestType createDepositRequestType() {
        return new DepositRequestType();
    }

    /**
     * Create an instance of {@link DepositResponse }
     * 
     */
    public DepositResponse createDepositResponse() {
        return new DepositResponse();
    }

    /**
     * Create an instance of {@link DepositOutputType }
     * 
     */
    public DepositOutputType createDepositOutputType() {
        return new DepositOutputType();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link NoteRequestType }
     * 
     */
    public NoteRequestType createNoteRequestType() {
        return new NoteRequestType();
    }

    /**
     * Create an instance of {@link NoteResponse }
     * 
     */
    public NoteResponse createNoteResponse() {
        return new NoteResponse();
    }

    /**
     * Create an instance of {@link NoteOutputType }
     * 
     */
    public NoteOutputType createNoteOutputType() {
        return new NoteOutputType();
    }

    /**
     * Create an instance of {@link ExtendDueDate }
     * 
     */
    public ExtendDueDate createExtendDueDate() {
        return new ExtendDueDate();
    }

    /**
     * Create an instance of {@link ExtendDueDateRequestType }
     * 
     */
    public ExtendDueDateRequestType createExtendDueDateRequestType() {
        return new ExtendDueDateRequestType();
    }

    /**
     * Create an instance of {@link ExtendDueDateResponse }
     * 
     */
    public ExtendDueDateResponse createExtendDueDateResponse() {
        return new ExtendDueDateResponse();
    }

    /**
     * Create an instance of {@link ExtendDueDateOutputType }
     * 
     */
    public ExtendDueDateOutputType createExtendDueDateOutputType() {
        return new ExtendDueDateOutputType();
    }

    /**
     * Create an instance of {@link AccountInactive }
     * 
     */
    public AccountInactive createAccountInactive() {
        return new AccountInactive();
    }

    /**
     * Create an instance of {@link AccountNotFound }
     * 
     */
    public AccountNotFound createAccountNotFound() {
        return new AccountNotFound();
    }

    /**
     * Create an instance of {@link DuplicateRequest }
     * 
     */
    public DuplicateRequest createDuplicateRequest() {
        return new DuplicateRequest();
    }

    /**
     * Create an instance of {@link InvalidNoteType }
     * 
     */
    public InvalidNoteType createInvalidNoteType() {
        return new InvalidNoteType();
    }

    /**
     * Create an instance of {@link InvalidPaymentAmount }
     * 
     */
    public InvalidPaymentAmount createInvalidPaymentAmount() {
        return new InvalidPaymentAmount();
    }

    /**
     * Create an instance of {@link InvalidTransSource }
     * 
     */
    public InvalidTransSource createInvalidTransSource() {
        return new InvalidTransSource();
    }

    /**
     * Create an instance of {@link InvalidTransType }
     * 
     */
    public InvalidTransType createInvalidTransType() {
        return new InvalidTransType();
    }

    /**
     * Create an instance of {@link NotEligibleForExtension }
     * 
     */
    public NotEligibleForExtension createNotEligibleForExtension() {
        return new NotEligibleForExtension();
    }

    /**
     * Create an instance of {@link SystemError }
     * 
     */
    public SystemError createSystemError() {
        return new SystemError();
    }

    /**
     * Create an instance of {@link TnNotFound }
     * 
     */
    public TnNotFound createTnNotFound() {
        return new TnNotFound();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link AccountInfoRequestRecordType }
     * 
     */
    public AccountInfoRequestRecordType createAccountInfoRequestRecordType() {
        return new AccountInfoRequestRecordType();
    }

    /**
     * Create an instance of {@link AccountInfoResponseRecordType }
     * 
     */
    public AccountInfoResponseRecordType createAccountInfoResponseRecordType() {
        return new AccountInfoResponseRecordType();
    }

    /**
     * Create an instance of {@link PayAndRestoreRequestRecordType }
     * 
     */
    public PayAndRestoreRequestRecordType createPayAndRestoreRequestRecordType() {
        return new PayAndRestoreRequestRecordType();
    }

    /**
     * Create an instance of {@link PayAndRestoreResponseRecordType }
     * 
     */
    public PayAndRestoreResponseRecordType createPayAndRestoreResponseRecordType() {
        return new PayAndRestoreResponseRecordType();
    }

    /**
     * Create an instance of {@link DepositRequestRecordType }
     * 
     */
    public DepositRequestRecordType createDepositRequestRecordType() {
        return new DepositRequestRecordType();
    }

    /**
     * Create an instance of {@link DepositResponseRecordType }
     * 
     */
    public DepositResponseRecordType createDepositResponseRecordType() {
        return new DepositResponseRecordType();
    }

    /**
     * Create an instance of {@link NoteRequestRecordType }
     * 
     */
    public NoteRequestRecordType createNoteRequestRecordType() {
        return new NoteRequestRecordType();
    }

    /**
     * Create an instance of {@link NoteResponseRecordType }
     * 
     */
    public NoteResponseRecordType createNoteResponseRecordType() {
        return new NoteResponseRecordType();
    }

    /**
     * Create an instance of {@link ExtendDueDateRequestRecordType }
     * 
     */
    public ExtendDueDateRequestRecordType createExtendDueDateRequestRecordType() {
        return new ExtendDueDateRequestRecordType();
    }

    /**
     * Create an instance of {@link ExtendDueDateResponseRecordType }
     * 
     */
    public ExtendDueDateResponseRecordType createExtendDueDateResponseRecordType() {
        return new ExtendDueDateResponseRecordType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.consolidated.com/cpi", name = "FeeAmount", scope = PayAndRestoreRequestRecordType.class)
    public JAXBElement<Long> createPayAndRestoreRequestRecordTypeFeeAmount(Long value) {
        return new JAXBElement<Long>(_PayAndRestoreRequestRecordTypeFeeAmount_QNAME, Long.class, PayAndRestoreRequestRecordType.class, value);
    }

}
