//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.17 at 12:55:15 PM IST 
//


package com.cci.payment.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PayAndRestoreResponseRecordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PayAndRestoreResponseRecordType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TrackingID" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="IsEligibleForRestore" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="NonRestoreReason" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="50"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="NewCurrentDueBalance" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="NewPastDueBalance" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayAndRestoreResponseRecordType", propOrder = {
    "trackingID",
    "isEligibleForRestore",
    "nonRestoreReason",
    "newCurrentDueBalance",
    "newPastDueBalance"
})
public class PayAndRestoreResponseRecordType {

    @XmlElement(name = "TrackingID")
    protected long trackingID;
    @XmlElement(name = "IsEligibleForRestore")
    protected boolean isEligibleForRestore;
    @XmlElement(name = "NonRestoreReason")
    protected String nonRestoreReason;
    @XmlElement(name = "NewCurrentDueBalance")
    protected long newCurrentDueBalance;
    @XmlElement(name = "NewPastDueBalance")
    protected long newPastDueBalance;

    /**
     * Gets the value of the trackingID property.
     * 
     */
    public long getTrackingID() {
        return trackingID;
    }

    /**
     * Sets the value of the trackingID property.
     * 
     */
    public void setTrackingID(long value) {
        this.trackingID = value;
    }

    /**
     * Gets the value of the isEligibleForRestore property.
     * 
     */
    public boolean isIsEligibleForRestore() {
        return isEligibleForRestore;
    }

    /**
     * Sets the value of the isEligibleForRestore property.
     * 
     */
    public void setIsEligibleForRestore(boolean value) {
        this.isEligibleForRestore = value;
    }

    /**
     * Gets the value of the nonRestoreReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonRestoreReason() {
        return nonRestoreReason;
    }

    /**
     * Sets the value of the nonRestoreReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonRestoreReason(String value) {
        this.nonRestoreReason = value;
    }

    /**
     * Gets the value of the newCurrentDueBalance property.
     * 
     */
    public long getNewCurrentDueBalance() {
        return newCurrentDueBalance;
    }

    /**
     * Sets the value of the newCurrentDueBalance property.
     * 
     */
    public void setNewCurrentDueBalance(long value) {
        this.newCurrentDueBalance = value;
    }

    /**
     * Gets the value of the newPastDueBalance property.
     * 
     */
    public long getNewPastDueBalance() {
        return newPastDueBalance;
    }

    /**
     * Sets the value of the newPastDueBalance property.
     * 
     */
    public void setNewPastDueBalance(long value) {
        this.newPastDueBalance = value;
    }

}
